### ISSUE TITLE
iOS の WebView Renderer で ATS 対応が必要

### ISSUE THREAD

**Issue by ytabuchi** [P3PPP/NakayokunaruHandsOn#1]
``` xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

を info.plist に追加します

**Comment by ayasesh** [comment]
追記
知らなかったのですが、Xamarin Studioもしくは Xcode上で直す必要がありそうです。
Vim等でのエディタで修正した所、アプリからではATSの対応がされていませんでした。

箇所を消して、NSAppTransportSecurityでkey追加して Dictionary指定からの NSAllowsArbitraryLoadsでのkey追加して Boolean指定からのtrueで無事対応できました。

対応は必要ないですが、共有まで

**Comment by ytabuchi** [comment]
Xamarin Studio で `info.plist` を開き、［ソース］タブを選択します。

［Add New Entry］をクリックして新規に項目を作り、

<img width="832" alt="2016-08-12 16 45 33" src="https://cloud.githubusercontent.com/assets/7854886/17616180/ff77bd52-60ad-11e6-82e0-77b0347fd75e.png">

「NSAppTransportSecurity」をコピペして項目から［Dictionary］を選択

<img width="404" alt="2016-08-12 16 46 15" src="https://cloud.githubusercontent.com/assets/7854886/17616187/0868f61a-60ae-11e6-80c5-90de7f8744d8.png">

ネストして表示される［Add New Entry］に「NSAllowsArbitraryLoads」をコピペして［Boolean］を選択

<img width="424" alt="2016-08-12 16 46 50" src="https://cloud.githubusercontent.com/assets/7854886/17616249/7c1c016a-60ae-11e6-8756-f2ca7db2047e.png">

［Yes］を選択して以下の状態にすれば OK です。

<img width="400" alt="2016-08-12 16 47 10" src="https://cloud.githubusercontent.com/assets/7854886/17616293/bf3aa4c4-60ae-11e6-9e19-28cbfd59270e.png">

@ayasesh おお？？私が Atom でやった時は大丈夫でしたが、Xamarin Studio で上記の標準のやり方でやるのが良さそうですね。

**Comment by ayasesh** [comment]
@ytabuchi 
僕もよく VSCodeでやるので問題ないと思っていました。
原因はわかりませんが言えることは y田淵さんの記述通りでやれば問題ないということです。
